/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
<<<<<<< HEAD
import { Route as TableUserTableImport } from './routes/table/user-table'
import { Route as ProfileViewProfileImport } from './routes/profile/view-profile'
=======
import { Route as ProfileIdImport } from './routes/profile/$id'
>>>>>>> sat/codeboard

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

<<<<<<< HEAD
const TableUserTableRoute = TableUserTableImport.update({
  id: '/table/user-table',
  path: '/table/user-table',
  getParentRoute: () => rootRoute,
} as any)

const ProfileViewProfileRoute = ProfileViewProfileImport.update({
  id: '/profile/view-profile',
  path: '/profile/view-profile',
=======
const ProfileIdRoute = ProfileIdImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
>>>>>>> sat/codeboard
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/table/user-table': {
      id: '/table/user-table'
      path: '/table/user-table'
      fullPath: '/table/user-table'
      preLoaderRoute: typeof TableUserTableImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
=======
  '/profile/$id': typeof ProfileIdRoute
>>>>>>> sat/codeboard
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
=======
  '/profile/$id': typeof ProfileIdRoute
>>>>>>> sat/codeboard
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
=======
  '/profile/$id': typeof ProfileIdRoute
>>>>>>> sat/codeboard
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths: '/' | '/profile/view-profile' | '/table/user-table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile/view-profile' | '/table/user-table'
  id: '__root__' | '/' | '/profile/view-profile' | '/table/user-table'
=======
  fullPaths: '/' | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile/$id'
  id: '__root__' | '/' | '/profile/$id'
>>>>>>> sat/codeboard
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  ProfileViewProfileRoute: typeof ProfileViewProfileRoute
  TableUserTableRoute: typeof TableUserTableRoute
=======
  ProfileIdRoute: typeof ProfileIdRoute
>>>>>>> sat/codeboard
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  ProfileViewProfileRoute: ProfileViewProfileRoute,
  TableUserTableRoute: TableUserTableRoute,
=======
  ProfileIdRoute: ProfileIdRoute,
>>>>>>> sat/codeboard
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
<<<<<<< HEAD
        "/profile/view-profile",
        "/table/user-table"
=======
        "/profile/$id"
>>>>>>> sat/codeboard
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
<<<<<<< HEAD
    "/profile/view-profile": {
      "filePath": "profile/view-profile.tsx"
    },
    "/table/user-table": {
      "filePath": "table/user-table.tsx"
=======
    "/profile/$id": {
      "filePath": "profile/$id.tsx"
>>>>>>> sat/codeboard
    }
  }
}
ROUTE_MANIFEST_END */
