/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TableUserTableImport } from './routes/table/user-table'
import { Route as ProfileViewProfileImport } from './routes/profile/view-profile'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TableUserTableRoute = TableUserTableImport.update({
  id: '/table/user-table',
  path: '/table/user-table',
  getParentRoute: () => rootRoute,
} as any)

const ProfileViewProfileRoute = ProfileViewProfileImport.update({
  id: '/profile/view-profile',
  path: '/profile/view-profile',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/view-profile': {
      id: '/profile/view-profile'
      path: '/profile/view-profile'
      fullPath: '/profile/view-profile'
      preLoaderRoute: typeof ProfileViewProfileImport
      parentRoute: typeof rootRoute
    }
    '/table/user-table': {
      id: '/table/user-table'
      path: '/table/user-table'
      fullPath: '/table/user-table'
      preLoaderRoute: typeof TableUserTableImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile/view-profile' | '/table/user-table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile/view-profile' | '/table/user-table'
  id: '__root__' | '/' | '/profile/view-profile' | '/table/user-table'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileViewProfileRoute: typeof ProfileViewProfileRoute
  TableUserTableRoute: typeof TableUserTableRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileViewProfileRoute: ProfileViewProfileRoute,
  TableUserTableRoute: TableUserTableRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile/view-profile",
        "/table/user-table"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile/view-profile": {
      "filePath": "profile/view-profile.tsx"
    },
    "/table/user-table": {
      "filePath": "table/user-table.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
